import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./(components)/Nav/Nav";
import MidCarousel from "./(components)/MidCarousel";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MegaMart",
  description: "Generated by me",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        <MidCarousel />
        {children}
      </body>
    </html>
  );
}
